### PR TITLE
fix: Update setup node action

### PR DESCRIPTION
**Pull request by oskarkivra**
BREAKING CHANGE:
- Using v3 of setup-node
- Removed `NODE_VERSION`, `PROJECT_ROOT`, `CACHE_CHILD_NODE_MODULES`, `CACHE_KEY` and `PATHS`

Usage change:
```diff
 uses: kivra/github_actions/setup-node@main
 with:
-  NODE_VERSION: 16.13.0
   NPM_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_WEB }}
-  CACHE_CHILD_NODE_MODULES: true
```

With `setup-node@v3` we can remove the need of manually specify the node version and set up the cache since that is now built-in.

We might not even need this shard action. These two examples are the same, but I still think it is nice to have this shared action.
```yml
uses: kivra/github_actions/setup-node@main
 with:
   NPM_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_WEB }}
```

```yml
- uses: actions/setup-node@v3
  with:
    node-version-file: 'package.json'
    registry-url: "https://npm.pkg.github.com"
    cache: 'npm'
    cache-dependency-path: "**/package-lock.json"
- name: 📀 Install
  run: npm ci
  shell: bash
  env:
    CI: "true"
    NODE_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
```

[Example run without cache](https://github.com/kivra/tf-web-goomba/actions/runs/3327627952/jobs/5502665680):
```
Resolved package.json as 16.13.1
Attempting to download 16.13.1...
Acquiring 16.13.1 - x64 from https://github.com/actions/node-versions/releases/download/16.13.1-1529449737/node-16.13.1-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/7f408855-f59f-461f-9509-e5f8180ac101 -f /home/runner/work/_temp/c1d26581-6c10-419a-8a18-cd6b7912a[25](https://github.com/kivra/tf-web-goomba/actions/runs/3327627952/jobs/5502665680#step:4:27)f
Adding to the cache ...
Done
Environment details
/opt/hostedtoolcache/node/16.13.1/x64/bin/npm config get cache
/home/runner/.npm
npm cache is not found
Run npm ci --ignore-scripts
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.

added 1[26](https://github.com/kivra/tf-web-goomba/actions/runs/3327627952/jobs/5502665680#step:4:28)2 packages, and audited 1[27](https://github.com/kivra/tf-web-goomba/actions/runs/3327627952/jobs/5502665680#step:4:29)3 packages in 46s

[29](https://github.com/kivra/tf-web-goomba/actions/runs/3327627952/jobs/5502665680#step:4:31)9 packages are looking for funding
  run `npm fund` for details
```

[Example run with cache](https://github.com/kivra/tf-web-goomba/actions/runs/3327710149/jobs/5502848673):
```
Resolved package.json as 16.13.1
Attempting to download 16.13.1...
Acquiring 16.13.1 - x64 from https://github.com/actions/node-versions/releases/download/16.13.1-1529449737/node-16.13.1-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/906570e7-fe06-4af2-a496-d8281ee820e8 -f /home/runner/work/_temp/b09b6[25](https://github.com/kivra/tf-web-goomba/actions/runs/3327710149/jobs/5502848673#step:4:27)1-2eb0-4899-861c-060595ff1d38
Adding to the cache ...
Done
Environment details
/opt/hostedtoolcache/node/16.13.1/x64/bin/npm config get cache
/home/runner/.npm
Received 0 of 109473761 (0.0%), 0.0 MBs/sec
Received 75497472 of 109473761 (69.0%), 35.9 MBs/sec
Received 109473761 of 109473761 (100.0%), 43.8 MBs/sec
Cache Size: ~104 MB (109473761 B)
/usr/bin/tar --use-compress-program unzstd -xf /home/runner/work/_temp/3c6db970-ac0d-42ee-8288-d6951c74a348/cache.tzst -P -C /home/runner/work/tf-web-goomba/tf-web-goomba
Cache restored successfully
Cache restored from key: node-cache-Linux-npm-d446fc672f96a8b13d97a907943f35048c51030297d670ec9cb097506fcfccd4
Run npm ci --ignore-scripts
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.

added 1[26](https://github.com/kivra/tf-web-goomba/actions/runs/3327710149/jobs/5502848673#step:4:28)2 packages, and audited 1[27](https://github.com/kivra/tf-web-goomba/actions/runs/3327710149/jobs/5502848673#step:4:29)3 packages in 19s

[29](https://github.com/kivra/tf-web-goomba/actions/runs/3327710149/jobs/5502848673#step:4:31)9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### CODE REVIEW

**Review by marcustisater-kivra — APPROVED** [review]
Nice!

**Comment by oskarkivra** [comment]
> Looking at the [docs for actions/setup-node](https://github.com/actions/setup-node#caching-global-packages-data) I'm slightly confused as to what is actually included in the cache

Nice finding. Hum... I have no idea but it is much faster with the cache but I might miss something. I can ask a question.

**Comment by oskarkivra** [comment]
I wrote a question here: https://github.com/actions/setup-node/issues/612

**Comment by oskarkivra** [comment]
I guess that they cache the dependencies somewhere but not `node_modules`. But I'm not sure at all.

**Comment by oskarkivra** [comment]
@eriklindebratt-kivra I got an answer:

> The action follows [actions/cache](https://github.com/actions/cache/blob/main/examples.md#node---npm) guidelines, and caches global cache on the machine instead of node_modules, so cache can be reused between different Node.js versions.

> Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci

So I'm not sure what the cache contain.

**Comment by oskarkivra** [comment]
@eriklindebratt-kivra, okay, this is what is stored in the cache: https://docs.npmjs.com/cli/v8/commands/npm-cache#details

**Comment by oskarkivra** [comment]
Dependent on https://github.com/kivra/github_actions/pull/13

**Pull request merged**
